apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app #consistent label across entire app
spec:
  containers: #One container per pod, so we only have 1 image. We can have multiple but rarely.
  - name: postgres
    image: postgres:9.4 #Note some images need you to specify these ENV
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name:  POSTGRES_PASSWORD
      value: "postgres"
    ports:
     - containerPort: 5432 #This is default for postgres to listen to.