apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379 #kubernetes service will listen on 6379 and forward data to 6379
      targetPort: 6379 #But which pod is listening on this port? We use Selector to "link" this service to redis pod
  selector:
    name: redis-pod
    app: demo-voting-app

#Because we did not specify NodePort or LoadBalancer type like we did in result/voting service, k8s will default
#service type to ClusterIP. When you kubectl get services, you will see ClusterIP for redis.