apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service #This is a result page, so no other pods need to contact it. Labels here doesn't mean anything.
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: result-app-pod #make sure this corresponds to your  pod
    app: demo-voting-app

#By default, all services uses ClusterIP and only internal pods can access. Since voting-app-pod is for external users,
#we change the service type to Load Balancer (or NodePort)
#To deploy these into GCP, you can check-in these definition files into your GitHub repository.
#Then gitclone this repository.