apiVersion: v1
kind: Pod
metadata:
   name: result-app-pod
   labels:
     name: result-app-pod
     app: demo-voting-app
spec:
  containers:
    - name: voting-app #One container per pod, so we only have 1 image. We can have multiple but rarely.
      image: dockersamples/examplevotingapp_result
      ports: #Added port to this pod definition
        - containerPort: 80 #because is web-app, we need to expose port